process.env.NTBA_FIX_319 = 1;
// npm install web3
const Web3 = require('web3')

const SIGNING_ADDRESS_PRIVATE_KEY = "8888888888888888888888888888888888888888888888888888888888888888"

const main = async () => {

  // Init RPC
  const web3 = new Web3('http://127.0.0.1:8545/')

  // Signer account
  const account = web3.eth.accounts.privateKeyToAccount(SIGNING_ADDRESS_PRIVATE_KEY)
  web3.eth.accounts.wallet.add(account)
  web3.eth.defaultAccount = account.address

  // Generate message
  const message = "put here the hash generated by the smart contract method formMessage(addressOfUserToBeWhitelisted)"

  // Sign it with the private key
  const signed = await web3.eth.accounts.sign(message, SIGNING_ADDRESS_PRIVATE_KEY)

  console.log({
  	signedBy: account.address,
  	signedMessage: signed
  })
}

main()
